---
- name: Bootstrap targets (python, base utils)
  hosts: all
  gather_facts: false
  roles:
    - role: bootstrap

- name: Setup Nginx reverse-proxy
  hosts: nginx_hosts
  gather_facts: true
  roles:
    - role: nginx

- name: Deploy Subscription API
  hosts: app_hosts
  gather_facts: true
  roles:
    - role: app
